### ISSUE TITLE
How or where to add java files, pom.xml file and other config in this structure

### ISSUE THREAD

**Issue by TEJAPS** [StephenOTT/ProcessProjectTemplate#10]
[](url)
![image](https://user-images.githubusercontent.com/29141451/84289246-e296d500-ab5f-11ea-8091-623dadbe1887.png)

This is the structure of spring-boot camunda
pom.xml has dependencies, 
resources folder have all bpmn,dmn and config files

**Comment by StephenOTT** [comment]
This structure is not designed for use with spring boot or a java app.  This structure is designed for when users are building standalone BPMN and scripts, and then deploying those into a exiting Camunda instance through the Camunda rest API

**Comment by TEJAPS** [comment]
so in this how we can add task listener or any other such delegates like we do in springboot : 
https://docs.camunda.org/manual/7.9/user-guide/process-engine/delegation-code/

**Comment by StephenOTT** [comment]
You will have to review the spring boot docs for Camunda.  This repository is not related to spring boot and does not have any ability to modify the Camunda engine (such as listener delegates)

**Comment by TEJAPS** [comment]
Is there any alternate way of using delegate method or execution/task listener in tomcat?
Apologies for such a late ask.

**Comment by StephenOTT** [comment]
You can using Scripting.  See the camunda scripting docs.
